-- Create Posts Table
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  excerpt TEXT,
  content TEXT NOT NULL, -- Rich text or markdown
  image_url TEXT,
  author_name TEXT DEFAULT 'Admin',
  published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE
);

-- Enable RLS
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Public Read Posts" ON posts FOR SELECT USING (published = true);
CREATE POLICY "Admins View All Posts" ON posts FOR SELECT USING (true); -- simplify for now, ideally check role
CREATE POLICY "Admins Insert Posts" ON posts FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins Update Posts" ON posts FOR UPDATE USING (true);
CREATE POLICY "Admins Delete Posts" ON posts FOR DELETE USING (true);


-- Storage for Blog Images
insert into storage.buckets (id, name, public) values ('blog', 'blog', true);

-- Update Public Access Policy to include new buckets
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id in ('products', 'categories', 'rooms', 'promos', 'blog') );

-- Update Authenticated Uploads Policy
DROP POLICY IF EXISTS "Authenticated Uploads" ON storage.objects;
create policy "Authenticated Uploads"
  on storage.objects for insert
  with check ( auth.role() = 'authenticated' );
