-- 1. SETUP FITUR BLOG/BERITA
-- =============================

-- Buat Tabel Posts
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  excerpt TEXT,
  content TEXT NOT NULL, -- Rich text or markdown
  image_url TEXT,
  author_name TEXT DEFAULT 'Admin',
  published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE
);

-- Enable RLS untuk Posts
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- Buat Policies untuk Posts (Mengijinkan semua orang membaca/menulis untuk dev mode)
CREATE POLICY "Public Read Posts" ON posts FOR SELECT USING (true);
CREATE POLICY "Public Update Posts" ON posts FOR UPDATE USING (true);
CREATE POLICY "Public Insert Posts" ON posts FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Delete Posts" ON posts FOR DELETE USING (true);


-- 2. SETUP STORAGE BUCKET (BLOG)
-- ==============================

-- Buat bucket 'blog' jika belum ada
insert into storage.buckets (id, name, public) values ('blog', 'blog', true)
ON CONFLICT (id) DO NOTHING;

-- Update Policy Public Access untuk semua bucket (termasuk blog)
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id in ('products', 'categories', 'rooms', 'promos', 'blog') );

-- Update Policy Upload untuk authenticated/anon (Dev Mode: izinkan anon upload)
DROP POLICY IF EXISTS "Authenticated Uploads" ON storage.objects;
create policy "Authenticated Uploads"
  on storage.objects for insert
  with check ( true ); -- Mengijinkan siapa saja upload (HANYA UNTUK DEV)

DROP POLICY IF EXISTS "Public Delete Objects" ON storage.objects;
create policy "Public Delete Objects"
  on storage.objects for delete
  using ( true ); -- Mengijinkan siapa saja delete file (HANYA UNTUK DEV)


-- 3. PERBAIKAN IZIN (FIX PERMISSIONS)
-- ===================================
-- Jalankan ini jika mengalami error "Gagal menghapus" atau permission denied

-- Pastikan role 'anon' dan 'authenticated' memiliki hak akses penuh ke tabel public
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated;

-- Pastikan RLS Policy untuk Products mengizinkan delete
DROP POLICY IF EXISTS "Users can delete their own products." ON products;
create policy "Enable delete for users" 
  on products for delete 
  using ( true );

-- Pastikan Foreign Key tidak menghalangi delete (Opsional, jika ada masalah FK)
-- ALTER TABLE products DROP CONSTRAINT IF EXISTS products_category_id_fkey;
-- ALTER TABLE products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL;
