-- Database Schema for Rupa Kayu

-- Create Categories Table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  base_price NUMERIC,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  image_url TEXT, -- Main image
  images TEXT[], -- Array of image URLs
  colors JSONB, -- Array of objects: { name, code, image }
  is_hero BOOLEAN DEFAULT FALSE,
  is_promo BOOLEAN DEFAULT FALSE,
  stock INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Create Policies (Allow public read, allow authenticated insert/update/delete)
create policy "Public categories are viewable by everyone."
  on categories for select
  using ( true );

create policy "Users can insert their own categories."
  on categories for insert
  with check ( true ); -- In production, restrict to authenticated users

create policy "Users can update their own categories."
  on categories for update
  using ( true );

create policy "Users can delete their own categories."
  on categories for delete
  using ( true );

create policy "Public products are viewable by everyone."
  on products for select
  using ( true );

create policy "Users can insert their own products."
  on products for insert
  with check ( true );

create policy "Users can update their own products."
  on products for update
  using ( true );

create policy "Users can delete their own products."
  on products for delete
  using ( true );

-- Insert initial data based on src/lib/data.ts (Optional, showing structure)
-- INSERT INTO categories (name, slug, image_url) VALUES ('KURSI', 'kursi', 'https://placehold.co/100x100/333/fff?text=Kursi');

-- STORAGE SETUP (Run this in Supabase SQL Editor if buckets are not created via dashboard)

-- 1. Create buckets
insert into storage.buckets (id, name, public) values ('products', 'products', true);
insert into storage.buckets (id, name, public) values ('categories', 'categories', true);

-- 2. Policy to allow public access to view images
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id in ('products', 'categories') );

-- 3. Policy to allow authenticated uploads (adjust for production)
create policy "Authenticated Uploads"
  on storage.objects for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated Updates"
  on storage.objects for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated Deletes"
  on storage.objects for delete
  using ( auth.role() = 'authenticated' );

-- ==========================================
-- NEW TABLES: ROOMS & PROMOS
-- ==========================================

-- Create Rooms (Inspirasi Ruang) Table
CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  items JSONB, -- Array of product IDs or objects e.g. [{id: 1, x: 50, y: 50}]
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Promos Table
CREATE TABLE IF NOT EXISTS promos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  discount_percentage NUMERIC,
  amount NUMERIC,
  image_url TEXT,
  valid_until TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE promos ENABLE ROW LEVEL SECURITY;

-- Create Policies for Rooms
CREATE POLICY "Public Read Rooms" ON rooms FOR SELECT USING (true);
CREATE POLICY "Public Write Rooms" ON rooms FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Rooms" ON rooms FOR UPDATE USING (true);
CREATE POLICY "Public Delete Rooms" ON rooms FOR DELETE USING (true);

-- Create Policies for Promos
CREATE POLICY "Public Read Promos" ON promos FOR SELECT USING (true);
CREATE POLICY "Public Write Promos" ON promos FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Promos" ON promos FOR UPDATE USING (true);
CREATE POLICY "Public Delete Promos" ON promos FOR DELETE USING (true);

-- STORAGE SETUP FOR ROOMS & PROMOS
-- 1. Create buckets
insert into storage.buckets (id, name, public) values ('rooms', 'rooms', true);
insert into storage.buckets (id, name, public) values ('promos', 'promos', true);

-- 2. Update Public Access Policy to include new buckets
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id in ('products', 'categories', 'rooms', 'promos') );

-- 3. Update Public Upload Policy (Dev Mode)
DROP POLICY IF EXISTS "Authenticated Uploads" ON storage.objects;
create policy "Authenticated Uploads"
  on storage.objects for insert

-- 4. Update 'products' table for separate Hero Image (transparent PNG)
ALTER TABLE products ADD COLUMN IF NOT EXISTS hero_image_url TEXT;
